/**
 * This file generated by AMFPHP 1.0
 * You can get AMFPHP to generate code customized to your preferences
 * By modifying the /browser/templates/as1.tpl file
 */

#include "NetServices.as"
#include "NetDebug.as"

defaultResponder = new Object();

NetServices.setDefaultGatewayUrl("http://<?php echo $info['server'] ?>/flashservices/gateway.php");
this.conn = NetServices.createGatewayConnection();
<?php if($info['auth']){ ?>this.conn.setCredentials("user", "pass");<?php } ?>

this.serv = conn.getService("<?php echo $info['package'] . $info['class'] ?>", defaultResponder)

<?php foreach($info['methods'] as $key => $method) { ?>
//<?php echo $method['description']; ?>

this.serv.<?php echo $method['methodName'] ?>(<?php echo $method['args']?>);
<?php } ?>

<?php foreach($info['methods'] as $key => $method) { ?>
defaultResponder.<?php echo $method['methodName']?>_Result = function(data)
{
	//Implement custom callback code
}

defaultResponder.<?php echo $method['methodName']?>_Status = function(info)
{
	//Implement custom callback code
}
<?php } ?>