/**
 * This file generated by AMFPHP 1.0
 * You can get AMFPHP to generate code customized to your preferences
 * By modifying the /browser/templates/testsuite.tpl file
 */

import clib.RemotingBatchTest;

class TestSuite
{
	function TestSuite()
	{
		init();
	}
	
	function init()
	{
		test = new RemotingBatchTest("http://<?php echo $info['server'] ?>/flashservices/gateway.php", <?php echo $info['package'] . $info['class'] ?>);
		
<?php foreach($info['methods'] as $key => $method) { ?>
		//<?php echo $method['description']?> 
		test.addTest('<?php echo $method['methodName']?>', [<?php echo $method['args']?>]);
<?php } ?>
		
		test.run();
	}
}